Ticket purchase branch
COSC310-Team-Passio/PassIO-COSC310-EventTicketProject pull request #99
Opened 2024-04-03 17:52 UTC by AngryMagnets

Currently, it displays all the tickets matching an event, and on event creation, 2 tickets are created at a price of 29.99$ I have not yet added payment method validation or changing how many tickets a user wants to buy

2024-04-03 21:35 UTC, Jared-Waldroff requested changes
Everything looks good, ticketing looks good, the changing of the meta data for html pages is good. The only thing I saw was the navbar was deleted from the checkout page. It should be left in as every page needs the navbar.

2024-04-03 21:35 UTC, Jared-Waldroff commented on PassIO/templates/checkout.html
> -  {% include 'navbar.html' %}
Why was the navbar removed from the checkout page?

2024-04-03 22:23 UTC, BryceD-4 commented
Ahh now I see what you meant about hyperlinking the text as an <a> tag instead of making it a button. I am ok with this if everyone else is. I was planning to bring up changing the method of "events_display" to the "events.html" on Friday. Lets chat about the ticket purchasing feature as I don't want to end up working on something that you are already working on. Once Jared's comment above is resolved, I feel it is good to merge.

2024-04-04 03:17 UTC, yukiiso approved these changes

2024-04-05 00:09 UTC, Jared-Waldroff approved these changes
Good changes! I like the changes you made to be able to purchase specific tickets.

2024-04-05 00:09 UTC, merged